#!/usr/bin/with-contenv bash
set -euo pipefail

# shellcheck source=/usr/lib/bashio/bashio.sh
source /usr/lib/bashio/bashio.sh

if ! bashio::config.true 'wireguard_enable'; then
  bashio::log.info "WireGuard disabled"
  exit 0
fi

config_json=$(bashio::addon.config)
private_key=$(bashio::config 'wireguard_private_key')
kill_switch=$(bashio::config 'wireguard_killswitch')
mtu=$(bashio::config 'wireguard_mtu')

if [[ -z "${private_key}" || "${private_key}" == "null" ]]; then
  bashio::log.error "WireGuard is enabled but no private key was provided"
  bashio::exit.nok
fi

if ! jq -e '.wireguard_peers | length > 0' >/dev/null 2>&1 <<<"${config_json}"; then
  bashio::log.error "WireGuard is enabled but no peers were provided"
  bashio::exit.nok
fi

mkdir -p /dev/net
if [[ ! -c /dev/net/tun ]]; then
  bashio::log.warning "/dev/net/tun is missing, creating device node"
  mknod /dev/net/tun c 10 200
  chmod 600 /dev/net/tun
fi

if [[ ! -c /dev/net/tun ]]; then
  bashio::log.error "/dev/net/tun is not available, WireGuard cannot start"
  bashio::exit.nok
fi

wg_conf=/etc/wireguard/wg0.conf
{
  echo "[Interface]"
  echo "PrivateKey = ${private_key}"
  if jq -e '.wireguard_address | length > 0' >/dev/null 2>&1 <<<"${config_json}"; then
    while IFS= read -r address; do
      [[ -n "${address}" ]] && echo "Address = ${address}"
    done < <(jq -r '.wireguard_address[]?' <<<"${config_json}")
  else
    bashio::log.error "WireGuard is enabled but no interface address was provided"
    bashio::exit.nok
  fi
  if jq -e '.wireguard_dns | length > 0' >/dev/null 2>&1 <<<"${config_json}"; then
    while IFS= read -r dns; do
      [[ -n "${dns}" ]] && echo "DNS = ${dns}"
    done < <(jq -r '.wireguard_dns[]?' <<<"${config_json}")
  fi
  if [[ -n "${mtu}" && "${mtu}" != "0" && "${mtu}" != "null" ]]; then
    echo "MTU = ${mtu}"
  fi

  peer_count=$(jq -r '.wireguard_peers | length' <<<"${config_json}")
  for ((i=0; i<peer_count; i++)); do
    peer=$(jq -c ".wireguard_peers[${i}]" <<<"${config_json}")
    public_key=$(jq -r '.public_key' <<<"${peer}")
    endpoint=$(jq -r '.endpoint' <<<"${peer}")
    preshared_key=$(jq -r '.preshared_key // empty' <<<"${peer}")
    persistent_keepalive=$(jq -r '.persistent_keepalive // empty' <<<"${peer}")

    echo ""
    echo "[Peer]"
    echo "PublicKey = ${public_key}"
    if [[ -n "${preshared_key}" ]]; then
      echo "PresharedKey = ${preshared_key}"
    fi
    echo "Endpoint = ${endpoint}"
    while IFS= read -r allowed_ip; do
      [[ -n "${allowed_ip}" ]] && echo "AllowedIPs = ${allowed_ip}"
    done < <(jq -r '.allowed_ips[]?' <<<"${peer}")
    if [[ -n "${persistent_keepalive}" ]]; then
      echo "PersistentKeepalive = ${persistent_keepalive}"
    fi
  done
} > "${wg_conf}"
chmod 600 "${wg_conf}"

if bashio::config.true 'diagnostics_enable'; then
  bashio::log.info "Diagnostics: current external IP before WireGuard: $(curl -fsSL https://ifconfig.co/ip || echo 'unavailable')"
  bashio::log.info "Diagnostics: resolv.conf before WireGuard: $(grep -E '^nameserver' /etc/resolv.conf | tr '\n' ' ')"
fi

if jq -e '.wireguard_dns | length > 0' >/dev/null 2>&1 <<<"${config_json}"; then
  cp /etc/resolv.conf /data/wireguard/resolv.conf.backup 2>/dev/null || true
  {
    echo "# Generated by karakeep_wg"
    jq -r '.wireguard_dns[]?' <<<"${config_json}" | while IFS= read -r dns; do
      [[ -n "${dns}" ]] && echo "nameserver ${dns}"
    done
  } > /etc/resolv.conf
fi

bashio::log.info "Starting WireGuard tunnel"
if ! wg-quick up wg0; then
  if [[ "${kill_switch}" == "true" ]]; then
    bashio::log.error "WireGuard failed to start and kill switch is enabled"
    bashio::exit.nok
  fi
  bashio::log.warning "WireGuard failed to start; continuing without tunnel"
  exit 0
fi

if [[ "${kill_switch}" == "true" ]]; then
  bashio::log.info "Applying WireGuard kill switch rules"
  iptables -P OUTPUT DROP
  iptables -A OUTPUT -o lo -j ACCEPT
  iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  iptables -A OUTPUT -o wg0 -j ACCEPT

  if jq -e '.wireguard_lan_subnets | length > 0' >/dev/null 2>&1 <<<"${config_json}"; then
    while IFS= read -r subnet; do
      [[ -n "${subnet}" ]] && iptables -A OUTPUT -d "${subnet}" -j ACCEPT
    done < <(jq -r '.wireguard_lan_subnets[]?' <<<"${config_json}")
  fi

  peer_count=$(jq -r '.wireguard_peers | length' <<<"${config_json}")
  for ((i=0; i<peer_count; i++)); do
    endpoint=$(jq -r ".wireguard_peers[${i}].endpoint" <<<"${config_json}")
    endpoint_host=${endpoint%:*}
    endpoint_port=${endpoint##*:}
    while IFS= read -r endpoint_ip; do
      [[ -n "${endpoint_ip}" ]] && iptables -A OUTPUT -d "${endpoint_ip}" -p udp --dport "${endpoint_port}" -j ACCEPT
    done < <(getent ahosts "${endpoint_host}" | awk '{print $1}' | sort -u)
  done
fi

if bashio::config.true 'diagnostics_enable'; then
  bashio::log.info "Diagnostics: WireGuard status: $(wg show wg0 | tr '\n' ' ')"
  bashio::log.info "Diagnostics: current external IP after WireGuard: $(curl -fsSL https://ifconfig.co/ip || echo 'unavailable')"
  bashio::log.info "Diagnostics: resolv.conf after WireGuard: $(grep -E '^nameserver' /etc/resolv.conf | tr '\n' ' ')"
fi
