###############
# AUTO BUILDS #
###############
# Those are the addon path filters used in the workflows to determine which addon needs to be build.
# name: slug/filename ; could be slug/config.* for all files
emby: emby/config.*
