komga:
  # libraries-scan-cron: "* */15 * * * ?" #periodic scan every 15 minutes
  libraries-scan-cron: "-" #disable periodic scan
  libraries-scan-startup: true #scan libraries at startup
  libraries-scan-directory-exclusions: #patterns to exclude directories from the scan
    - "#recycle" #synology NAS recycle bin
    - "@eaDir" #synology NAS index/metadata folders
  remember-me:
    key: changeMe! #required to activate the remember-me auto-login via cookies
    validity: 2592000 #validity of the cookie in seconds, here 1 month
  database:
    file: /data/komga/database.sqlite
  database-backup:
    path: /share/komga/database-backup.zip
    schedule: "0 0 */6 * * ?" #every 6 hours
    enabled: true
    startup: true
server:
  port: 8080
  servlet.context-path: /komga
